# Generated by Django 6.0.4 on 2026-04-20 00:51

import django.db.models.deletion
from decimal import Decimal

from django.db import migrations, models
from django.db.models import Sum


def forwards_recompute_agent_counters(apps, schema_editor):
    """Align denormalized marketing-agent fields with unsettled sales (no payout lines yet)."""
    MarketingAgent = apps.get_model('api', 'MarketingAgent')
    Sale = apps.get_model('api', 'Sale')
    for agent in MarketingAgent.objects.all():
        qs = Sale.objects.filter(sales_person_id=agent.id)
        agent.total_sales = qs.count()
        agg = qs.aggregate(rev=Sum('total_amount'), comm=Sum('commission_amount'))
        agent.total_revenue = agg['rev'] or Decimal('0')
        agent.pending_commission_total = agg['comm'] or Decimal('0')
        agent.customers_referred = qs.values('customer_id').distinct().count()
        agent.save(
            update_fields=[
                'total_sales',
                'total_revenue',
                'customers_referred',
                'pending_commission_total',
            ],
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_editrequest_marketingagent_customers_referred_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingagent',
            name='pending_commission_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.CreateModel(
            name='CommissionPayoutBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_commission', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sale_count', models.PositiveIntegerField(default=0)),
                ('note', models.TextField(blank=True, null=True)),
                ('marketing_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_batches', to='api.marketingagent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommissionPayoutLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='api.commissionpayoutbatch')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_payout_lines', to='api.sale')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('sale',), name='commission_payoutline_unique_sale')],
            },
        ),
        migrations.RunPython(forwards_recompute_agent_counters, noop_reverse),
    ]
