# Generated by Django 5.2.13 on 2026-07-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_sale_sale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('agent', 'Agent'), ('accountant', 'Accountant'), ('marketing', 'Marketing')], default='agent', max_length=20),
        ),
    ]
